// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package tutorial

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID       int64
	Owner    string
	Balance  int64
	Currency string
	CreateAt pgtype.Timestamptz
}

type Entry struct {
	ID        int64
	AccountID int64
	// can be negative or positive
	Account  int64
	CreateAt pgtype.Timestamptz
}

type Transfer struct {
	ID            int64
	FromAccountID int64
	ToAccountID   int64
	// must be positive
	Account  int64
	CreateAt pgtype.Timestamptz
}
